using System;
using System.Collections.Generic;

#nullable disable

namespace MyLabOrdersApi.Models
{
    public partial class WebPatreq
    {
        public bool? Posted { get; set; }
        public int Accno { get; set; }
        public string ReqId { get; set; }
        public DateTime? Accdate { get; set; }
        public string Ssno { get; set; }
        public string PatChart { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string Mi { get; set; }
        public DateTime? Dob { get; set; }
        public double? Age { get; set; }
        public string Sex { get; set; }
        public string Addrstr1 { get; set; }
        public string Addrstr2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Inscd1 { get; set; }
        public string Insno1 { get; set; }
        public string Inscd2 { get; set; }
        public string Insno2 { get; set; }
        public string Billto { get; set; }
        public string Groupno { get; set; }
        public string Billsprof { get; set; }
        public string Billprof { get; set; }
        public string Telno { get; set; }
        public double? Docno { get; set; }
        public string Docno1 { get; set; }
        public double? Docno2 { get; set; }
        public double? Docno3 { get; set; }
        public DateTime? Dtdrawn { get; set; }
        public string Tmdrawn { get; set; }
        public DateTime? Dtrecvd { get; set; }
        public string Tmrecvd { get; set; }
        public DateTime? Repdate { get; set; }
        public string Reptime { get; set; }
        public string Seclevel { get; set; }
        public bool? Complete { get; set; }
        public bool? Printed { get; set; }
        public string Dcode { get; set; }
        public string Dcode1 { get; set; }
        public string Dcode2 { get; set; }
        public string Dcode3 { get; set; }
        public string Dcode4 { get; set; }
        public string Dcode5 { get; set; }
        public string Specrecv { get; set; }
        public string Billstatus { get; set; }
        public bool? AcctTrans { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public string Comment4 { get; set; }
        public string Comment5 { get; set; }
        public string Comment6 { get; set; }
        public string Comment7 { get; set; }
        public string Commentw1 { get; set; }
        public bool? Saved { get; set; }
        public DateTime? RepInitdt { get; set; }
        public DateTime? RepLastdt { get; set; }
        public string DirNo { get; set; }
        public string Siteno { get; set; }
        public string Reltosub { get; set; }
        public string Subinsno { get; set; }
        public string Sublname { get; set; }
        public string Subfname { get; set; }
        public string Submi { get; set; }
        public string Subgen { get; set; }
        public string Subsex { get; set; }
        public DateTime? Subdob { get; set; }
        public string Subempst { get; set; }
        public string Suppinsind { get; set; }
        public string NursingHome { get; set; }
        public string RoomOrWard { get; set; }
        public string RepeatOrder { get; set; }
        public string RepeatOrderFor { get; set; }
        public string CellPhone { get; set; }
        public string EmailAddress { get; set; }
        public string WorkPhone { get; set; }
        public string DoctorName { get; set; }
        public string SubSsno { get; set; }
        public string Username { get; set; }
        public string ModifyingUsername { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public bool? PostedToBilling { get; set; }
        public bool? Release { get; set; }
        public int? NursingHomeId { get; set; }
        public string GroupNo2 { get; set; }
        public string Race { get; set; }
        public string GroupName1 { get; set; }
        public string GroupName2 { get; set; }
        public string GroupName3 { get; set; }
        public int? AutoBill1 { get; set; }
        public int? AcceptAssign1 { get; set; }
        public string Authorization1 { get; set; }
        public DateTime? EffectiveFrom1 { get; set; }
        public DateTime? EffectiveTo1 { get; set; }
        public int? AutoBill2 { get; set; }
        public int? AcceptAssign2 { get; set; }
        public string Authorization2 { get; set; }
        public DateTime? EffectiveFrom2 { get; set; }
        public DateTime? EffectiveTo2 { get; set; }
        public int? AutoBill3 { get; set; }
        public int? AcceptAssign3 { get; set; }
        public string Authorization3 { get; set; }
        public DateTime? EffectiveFrom3 { get; set; }
        public DateTime? EffectiveTo3 { get; set; }
        public string Inscd3 { get; set; }
        public string Insno3 { get; set; }
        public string Groupno3 { get; set; }
        public string Dcode6 { get; set; }
        public string Dcode7 { get; set; }
        public string Dcode8 { get; set; }
        public string Dcode9 { get; set; }
        public string Dcode10 { get; set; }
        public string Dcode11 { get; set; }
        public string Ins1Subscriber { get; set; }
        public string Ins2Subscriber { get; set; }
        public string Ins3Subscriber { get; set; }
        public string Location { get; set; }
        public bool? Emailed { get; set; }
        public bool? Faxed { get; set; }
        public string RequisitionType { get; set; }
        public string AssignmentOfBenefits { get; set; }
        public string ReleaseofInformation { get; set; }
        public string SignatureSource { get; set; }
        public string Reltosub2 { get; set; }
        public string PatientId2 { get; set; }
        public string PatientId3 { get; set; }
        public bool? Hl7transmitted { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string ResponsiblePartyCode { get; set; }
        public string RelToResParty { get; set; }
        public bool? Stat { get; set; }
        public string SpecCollectorId { get; set; }
        public int? CopyToId { get; set; }
        public string CopyToName { get; set; }
        public string PracticeName { get; set; }
        public string OfficeName { get; set; }
        public bool? NoMedication { get; set; }
        public string PrintedBy { get; set; }
        public string ReleasedBy { get; set; }
        public string ReportStatus { get; set; }
        public string Source { get; set; }
        public string AltSource { get; set; }
        public string Ethnicity { get; set; }
        public string DlicenseNo { get; set; }
        public string Image { get; set; }
    }
}
